# Generated by Django 3.1 on 2020-11-06 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, db_index=True, max_length=25, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expired', models.DateTimeField()),
                ('score_multiplier', models.IntegerField(default=1)),
                ('score', models.IntegerField(default=0)),
                ('bank', models.IntegerField(default=0)),
                ('tmp_score', models.IntegerField(default=0)),
                ('round', models.IntegerField(default=1)),
                ('state', models.CharField(choices=[('waiting_for_players', 'waiting_for_players'), ('intro', 'intro'), ('questions', 'questions'), ('weakest_choose', 'weakest_choose'), ('weakest_reveal', 'weakest_reveal'), ('final', 'final'), ('final_questions', 'final_questions'), ('end', 'end')], default='waiting_for_players', max_length=25)),
                ('timer', models.BigIntegerField(default=0)),
                ('bank_timer', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('is_final', models.BooleanField()),
                ('is_answered_correctly', models.BooleanField(null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('is_correct', models.BooleanField(null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='weakest.game')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('is_weak', models.BooleanField(default=False)),
                ('right_answers', models.IntegerField(default=0)),
                ('bank_income', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='weakest.game')),
                ('weak', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='weakest.player')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='answerer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='weakest.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='weakest.question'),
        ),
        migrations.AddField(
            model_name='game',
            name='strongest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='weakest.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='weakest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='weakest.player'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_final'], name='weakest_que_is_fina_e99d39_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_processed'], name='weakest_que_is_proc_645278_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['is_weak'], name='weakest_pla_is_weak_f0dda0_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['token'], name='weakest_gam_token_8150f2_idx'),
        ),
    ]
