# Generated by Django 3.1 on 2020-11-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weakest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='round',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='game',
            name='score_multiplier',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='tmp_score',
            field=models.IntegerField(default=0),
        ),
    ]
