# Generated by Django 3.1 on 2020-11-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weakest', '0002_auto_20201101_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='bank',
            field=models.IntegerField(default=0),
        ),
    ]
