# Generated by Django 3.1 on 2020-11-02 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weakest', '0003_game_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='bank_timer',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='weak',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='weakest.player'),
        ),
    ]
