# Generated by Django 3.1 on 2020-11-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weakest', '0006_auto_20201104_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='round',
            field=models.IntegerField(default=1),
        ),
    ]
