# Generated by Django 3.1 on 2020-11-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weakest', '0007_auto_20201105_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_answered_correctly',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='is_correct',
            field=models.BooleanField(null=True),
        ),
    ]
