# Generated by Django 3.1 on 2020-10-21 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, db_index=True, max_length=25, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expired', models.DateTimeField()),
                ('last_round', models.IntegerField(default=1)),
                ('final_round', models.IntegerField(default=0)),
                ('state', models.CharField(choices=[('waiting_for_players', 'waiting_for_players'), ('themes_all', 'themes_all'), ('round_themes', 'round_themes'), ('questions', 'questions'), ('question_event', 'question_event'), ('question', 'question'), ('question_end', 'question_end'), ('final_themes', 'final_themes'), ('final_bets', 'final_bets'), ('final_question', 'final_question'), ('final_question_timer', 'final_question_timer'), ('final_end', 'final_end'), ('game_end', 'game_end')], default='waiting_for_players', max_length=25)),
                ('round', models.IntegerField(default=1)),
                ('question_bet', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('round', models.IntegerField(db_index=True)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='jeopardy.game')),
            ],
            options={
                'ordering': ['round', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_theme', models.CharField(max_length=255, null=True)),
                ('text', models.TextField(null=True)),
                ('image', models.CharField(max_length=255, null=True)),
                ('audio', models.CharField(max_length=255, null=True)),
                ('video', models.CharField(max_length=255, null=True)),
                ('answer', models.CharField(max_length=255)),
                ('answer_text', models.TextField(null=True)),
                ('answer_image', models.CharField(max_length=255, null=True)),
                ('answer_audio', models.CharField(max_length=255, null=True)),
                ('answer_video', models.CharField(max_length=255, null=True)),
                ('value', models.IntegerField()),
                ('comment', models.TextField()),
                ('type', models.CharField(choices=[('standard', 'standard'), ('auction', 'auction'), ('bagcat', 'bagcat')], max_length=25)),
                ('is_processed', models.BooleanField(default=False)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='jeopardy.theme')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('balance', models.IntegerField(default=0)),
                ('final_bet', models.IntegerField(default=0)),
                ('final_answer', models.TextField(blank=True, default='')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='jeopardy.game')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='answerer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='jeopardy.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='jeopardy.question'),
        ),
    ]
