# Generated by Django 3.1 on 2020-10-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_audio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_image',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_video',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='audio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='video',
            field=models.TextField(null=True),
        ),
    ]
