# Generated by Django 3.1 on 2020-11-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='state',
            field=models.CharField(choices=[('waiting_for_players', 'waiting_for_players'), ('intro', 'intro'), ('themes_all', 'themes_all'), ('round', 'round'), ('round_themes', 'round_themes'), ('questions', 'questions'), ('question_event', 'question_event'), ('question', 'question'), ('answer', 'answer'), ('question_end', 'question_end'), ('final_themes', 'final_themes'), ('final_bets', 'final_bets'), ('final_question', 'final_question'), ('final_answer', 'final_answer'), ('final_player_answer', 'final_player_answer'), ('final_player_bet', 'final_player_bet'), ('game_end', 'game_end')], default='waiting_for_players', max_length=25),
        ),
    ]
