# Generated by Django 3.1.4 on 2020-12-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0002_auto_20201101_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='early_answerers',
            field=models.ManyToManyField(related_name='_game_early_answerers_+', to='jeopardy.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='early_answerers_invoked',
            field=models.BooleanField(default=False),
        ),
    ]
