# Generated by Django 3.1 on 2020-10-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0002_auto_20201025_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
