# Generated by Django 3.1.4 on 2021-01-18 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, db_index=True, max_length=25, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expired', models.DateTimeField()),
                ('round', models.IntegerField(default=1)),
                ('state', models.CharField(choices=[('waiting_for_teams', 'waiting_for_teams'), ('intro', 'intro'), ('round', 'round'), ('button', 'button'), ('answers', 'answers'), ('answers_reveal', 'answers_reveal'), ('final', 'final'), ('final_questions', 'final_questions'), ('final_questions_reveal', 'final_questions_reveal'), ('end', 'end')], default='waiting_for_teams', max_length=25)),
                ('timer', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('strikes', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('final_score', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='feud.game')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_final', models.BooleanField()),
                ('is_processed', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='feud.game')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='answerer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='feud.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='feud.question'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('value', models.IntegerField()),
                ('is_opened', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='feud.question')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_final'], name='feud_questi_is_fina_a625b7_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_processed'], name='feud_questi_is_proc_712370_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['token'], name='feud_game_token_f5c193_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['is_opened'], name='feud_answer_is_open_6a3696_idx'),
        ),
    ]
