# Generated by Django 3.1.4 on 2021-03-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_final_answered',
            field=models.BooleanField(default=False),
        ),
    ]
