# Generated by Django 3.1.4 on 2020-12-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whirligig', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='state',
            field=models.CharField(choices=[('start', 'start'), ('intro', 'intro'), ('questions', 'questions'), ('question_whirligig', 'question_whirligig'), ('question_start', 'question_start'), ('question_discussion', 'question_discussion'), ('answer', 'answer'), ('right_answer', 'right_answer'), ('question_end', 'question_end'), ('end', 'end')], default='start', max_length=25),
        ),
    ]
