# Generated by Django 3.1 on 2020-10-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whirligig', '0003_auto_20201011_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='state',
            field=models.CharField(choices=[('start', 'start'), ('intro', 'intro'), ('questions', 'questions'), ('question_start', 'question_start'), ('question_discussion', 'question_discussion'), ('answer', 'answer'), ('right_answer', 'right_answer'), ('question_end', 'question_end'), ('end', 'end')], default='start', max_length=25),
        ),
        migrations.AlterField(
            model_name='game',
            name='token',
            field=models.CharField(blank=True, db_index=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='gameitem',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
