# Generated by Django 3.1 on 2020-10-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whirligig', '0003_auto_20200930_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='timer_paused_time',
            field=models.IntegerField(default=0),
        ),
    ]
