# Generated by Django 3.1 on 2020-10-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whirligig', '0004_game_timer_paused_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameitem',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
